 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/premium-buckeye-281615/github.com/siebever/international-project-cors:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/premium-buckeye-281615/github.com/siebever/international-project-cors:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'premium-buckeye-281615'
   - '--image'
   - 'gcr.io/premium-buckeye-281615/github.com/siebever/international-project-cors:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated'
 images:
 - 'gcr.io/premium-buckeye-281615/github.com/siebever/international-project-cors:$COMMIT_SHA'
